# Generated by Django 4.2.10 on 2024-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/account_3033143.png', upload_to='profile_photos/'),
        ),
    ]
