# Generated by Django 4.2.10 on 2024-02-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='minutes_to_read',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
